[package]
org = "thishanicharles"
name = "httptest"
version = "0.1.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

# [[dependency]]
# org="ballerina"
# name="http"
# version="2.8.1"